### PR TITLE
Automated tcp and macswap integration tests

### PR DESCRIPTION
**Pull request by sirspinach**
This test reads in a pcap file consisting of a simple HTTP request and
response, and confirms that the reconstructed TCP stream matches the expected payload.

### CODE REVIEW

**Comment by sirspinach** [comment]
@apanda: Should hugepages be initialized in the container? https://travis-ci.org/sirspinach/NetBricks/builds/242093729#L3817

**Comment by sirspinach** [comment]
The second test is just a simple macswap test that confirms that src/dst mac addresses are changed around.

**Comment by sirspinach** [comment]
@apanda: The macswap test requires that the build container have tcpdump installed. When you get a chance, could you push the Docker image from this commit's updated Dockerfile to Docker Hub?

**Comment by apanda** [comment]
Thanks Merged.

**Pull request merged**
